"""
Django settings for ai_agent project.

Generated by 'django-admin startproject' using Django 5.2.9.
"""
import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings
SECRET_KEY = 'django-insecure-unviry@m2hjj2ztaw3h0@66ci)^a-jh=5u*7s50wy%iq08)mjg'

DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'agent_app',
    'drf_yasg',
    # 🔐 DRF + JWT
    'rest_framework',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]
# Allow your frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3001",
    "http://localhost:5173",
    "http://localhost:3000"
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-client-id",   # 🔥 VERY IMPORTANT (you are sending this)
]
ROOT_URLCONF = 'ai_agent.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ai_agent.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME", ""),
        'USER': os.getenv("DB_USER", ""),
        'PASSWORD': os.getenv("DB_PASSWORD", ""),
        'HOST': os.getenv("DB_HOST", ""),
        'PORT': os.getenv("DB_PORT", ""),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files
STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'agent_app.User'


# ------------------ CUSTOM PROJECT SETTINGS ------------------

# OpenAI key
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# # Chroma persistence directory
# CHROMA_PERSIST_DIR = os.getenv(
#     "CHROMA_PERSIST_DIR",
#     str(BASE_DIR / "chroma_db")
# )
#
# # Document upload directory
# UPLOAD_DOCUMENTS_DIR = os.getenv(
#     "UPLOAD_DOCUMENTS_DIR",
#     str(BASE_DIR / "uploaddocuments")
# )
#
# # Ensure directories exist
# os.makedirs(CHROMA_PERSIST_DIR, exist_ok=True)
# os.makedirs(UPLOAD_DOCUMENTS_DIR, exist_ok=True)

# Get user's home directory for cross-platform compatibility
HOME_DIR = Path.home()

# Chroma persistence directory - expand ~ to home directory
CHROMA_PERSIST_DIR = os.getenv("CHROMA_PERSIST_DIR")
if CHROMA_PERSIST_DIR:
    # Expand ~ to actual home directory path
    CHROMA_PERSIST_DIR = os.path.expanduser(CHROMA_PERSIST_DIR)
else:
    # Fallback to home directory
    CHROMA_PERSIST_DIR = str(HOME_DIR / "limelight-documents" / "chatBot-training-data" / "chroma_db")

# Document upload directory - expand ~ to home directory
UPLOAD_DOCUMENTS_DIR = os.getenv("UPLOAD_DOCUMENTS_DIR")
if UPLOAD_DOCUMENTS_DIR:
    # Expand ~ to actual home directory path
    UPLOAD_DOCUMENTS_DIR = os.path.expanduser(UPLOAD_DOCUMENTS_DIR)
else:
    # Fallback to home directory
    UPLOAD_DOCUMENTS_DIR = str(HOME_DIR / "limelight-documents" / "chatBot-training-data" / "uploaddocuments")

# Ensure directories exist
os.makedirs(CHROMA_PERSIST_DIR, exist_ok=True)
os.makedirs(UPLOAD_DOCUMENTS_DIR, exist_ok=True)


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "standard": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },

    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },

    "loggers": {
        # your app logger
        "agent_app": {
            "handlers": ["console"],
            "level": "DEBUG",   # change to INFO if you want
            "propagate": False,
        },
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

# drf-yasg / Swagger configuration to allow entering Bearer tokens in UI
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}